### ISSUE TITLE
Update MenuBar contents dynamically?

### ISSUE THREAD

**Issue by kiwiandroiddev** [0x4a616e/NSMenuFX#14]
What is the recommended approach to update the MenuBar contents at runtime, sometime after Application start? For instance, adding or removing Menus or disabling particular MenuItems depending on the application state.

Keeping a reference to the MenuBar passed to `setGlobalMenuBar` and adding/removing items etc. later seems to have no effect, nor does building and setting an entirely new MenuBar.

Happy to send a PR with a new sample and doc entry for this once it's clear.

Thanks for the library!

**Comment by 0x4a616e** [comment]
Hi Matt, thanks for the report. Are we talking about the application menu or any other menu? Can you maybe provide a small snippet just of the update you're trying to make?

**Comment by kiwiandroiddev** [comment]
In this case I was trying to add a new menu to the system menu bar after the app is in a logged-in/connected state. Here's a snippet; this function is called from the Application's `start()` method:
```kotlin
fun setupMenuBar() {
        val tk = MenuToolkit.toolkit()
        val menuBar = MenuBar()
        val appMenu = Menu(AppName)
        appMenu.getItems().addAll(
            tk.createNativeAboutMenuItem(AppName),
            SeparatorMenuItem(),
            tk.createHideMenuItem(AppName),
            tk.createHideOthersMenuItem(),
            tk.createUnhideAllMenuItem(),
            SeparatorMenuItem(),
            tk.createQuitMenuItem(AppName)
        )

        val fileMenu = Menu("File")
        val newItem = MenuItem("New...")
        fileMenu.items.addAll(
            newItem, SeparatorMenuItem(), tk.createCloseWindowMenuItem(),
            SeparatorMenuItem(), MenuItem("TBD")
        )

        menuBar.menus.addAll(appMenu, fileMenu)
        tk.setMenuBar(menuBar)

        runLater(Duration(2000.0)) {
            val testMenu = Menu("Test").apply {
                items.addAll(MenuItem("TBD"))
            }
            menuBar.menus.addAll(testMenu)          // not shown
        }
}
```

**Comment by 0x4a616e** [comment]
You're right, that was something i missed. I just pushed a new version `3.1.0` which should fix this issue with one limitation: You cannot start with an empty MenuBar and start adding elements there. It will not fail, but then you'll miss the first menu... The reason is that the first menu item requires some special handling which is _only_ there when the menu bar is newly set. Everything else can now be modified and changes should be reflected immediately now. It would be great if you could confirm if this is working for you now.
