### ISSUE TITLE
3.0.0-BETA2 Events not working all of the time

### ISSUE THREAD

**Issue by vewert** [0x4a616e/NSMenuFX#3]
I migrated from the old version(2.1.8) to 3.0.0-BETA2, which was very straight forward.

When I try running my application, however, I noticed that the MenuItem events aren't always working. For example, when I click on the _About_ menu item, or the _Preferences_ menu item (that I created), the events don't work consistently. They work sometimes, but not all the time (seem to work about 10% of the time). Same thing when I try the _Quit_ menu item; sometimes the application exits, but mostly not.

The code I am using, is the same as for the old version, and when I revert to the the older version, the events work was expected.

I also tried using the defaultApplicationMenu (using `createDefaultApplicationMenu()`), but the same problem occurs.

I'm not sure why sometimes it works and sometimes not; maybe a timing issue.

Also note: I am using JavaFX 15.0.1. (I'm not sure if that matters.)

**Comment by 0x4a616e** [comment]
Hi @vewert , thank you for the report and sorry for the inconvenience. I also noticed this issue recently and i already have a fix ready. The problem is, that the objects that were being called back from native code sometimes got garbage collected as no further reference existed within Java. I'm now keeping an extra reference to prevent that ;) I'm planing to release the fix as 3.0.0 today or tomorrow, as there are no further API changes planned so far.

**Comment by 0x4a616e** [comment]
I just published

```
<dependency>
  <groupId>de.jangassen</groupId>
  <artifactId>nsmenufx</artifactId>
  <version>3.0.0</version>
</dependency>
```

it should be available within a few minutes. Maybe you can confirm if things are working now.

**Comment by vewert** [comment]
I updated to 3.0.0, and the Events seem to be working properly now!

Thanks!
